name: GitHub actions Reusable Workflow
run-name: GitHub Action Reusable Workflow
on:
  
  workflow_call:
jobs:
  Basic-Workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Job is executing a Reusable Workflow"
